package builders

import client.WsClient
import play.api.libs.json.JsValue
import play.api.libs.ws.StandaloneWSResponse
import utils.BaseRequests

object PropertyAssessmentRequestBuilder extends BaseRequests {

  def propertyAssessmentRequest(credId: String, assessmentId: String): StandaloneWSResponse = {
    val bearerToken = createBearerToken(credId = credId)
    val baseUri     = s"$bridgeIntegrationUrl/property-assessment/$credId/assessment/$assessmentId"
    println(s"service level bearer token ********************************* $bearerToken")
    val headers     = Map(
      "Authorization" -> s"Bearer $bearerToken",
      "Content-Type"  -> "application/json",
      "Accept"        -> "application/vnd.hmrc.1.0+json"
    )

    val json: JsValue = play.api.libs.json.Json.parse("""
        {"properties" : [ {                                                                                                                                                                                                                          
    "id" : 13,                                                                                                                                                                                                                                
    "idx" : "1.13.1",                                                                                                                                                                                                                         
    "name" : "Property Link",                                                                                                                                                                                                                 
    "label" : "Ratepayer-ListEntry-Property",                                                                                                                                                                                                 
    "description" : "A relationships between LGFA88shd9para4J person-personas and LGFA88 hereditaments for which such personas are obliged to provide LGFA88shd9para4I(1) notofiable information.",                                           
    "origination" : null,                                                                                                                                                                                                                     
    "termination" : null,                                                                                                                                                                                                                     
    "category" : {                                                                                                                                                                                                                            
      "code" : "LTX-DOM-REL",                                                                                                                                                                                                                 
      "meaning" : "Local taxation domain relationship"                                                                                                                                                                                        
    },                                                                                                                                                                                                                                        
    "type" : {                                                                                                                                                                                                                                
      "code" : "LIB",                                                                                                                                                                                                                         
      "meaning" : "Liability | One entity is liable for other entity(s)"                                                                                                                                                                      
    },                                                                                                                                                                                                                                        
    "class" : {                                                                                                                                                                                                                               
      "code" : "LOC",                                                                                                                                                                                                                         
      "meaning" : "Local Non Domestic Rating Occupied Hereditament Charge"                                                                                                                                                                    
    },                                                                                                                                                                                                                                        
    "data" : {                                                                                                                                                                                                                                
      "foreign_ids" : [ ],                                                                                                                                                                                                                    
      "foreign_names" : [ ],                                                                                                                                                                                                                  
      "foreign_labels" : [ ],                                                                                                                                                                                                                 
      "manifestations" : [ {                                                                                                                                                                                                                  
        "artifact_reference" : null,                                                                                                                                                                                                          
        "artifact_code" : "NRB",                                                                                                                                                                                                              
        "artifact_description" : null,                                                                                                                                                                                                        
        "issued_date" : null,                                                                                                                                                                                                                 
        "withdrawn_date" : null,                                                                                                                                                                                                              
        "effective_from_date" : null,                                                                                                                                                                                                         
        "effective_to_date" : null,                                                                                                                                                                                                           
        "observed_date" : null,                                                                                                                                                                                                               
        "operative_area_code" : null,                                                                                                                                                                                                         
        "operative_area_name" : null,                                                                                                                                                                                                         
        "protodata_ptr" : "https://hmrc/sdes/yry64849ree",                                                                                                                                                                                    
        "notes" : null                                                                                                                                                                                                                        
      } ]                                                                                                                                                                                                                                     
    },                                                                                                                                                                                                                                        
    "protodata" : [ ],                                                                                                                                                                                                                        
    "metadata" : {                                                                                                                                                                                                                            
      "sending" : {                                                                                                                                                                                                                           
        "extracting" : {                                                                                                                                                                                                                      
          "selecting" : { },                                                                                                                                                                                                                  
          "filtering" : { },                                                                                                                                                                                                                  
          "supplementing" : { },                                                                                                                                                                                                              
          "recontextualising" : { },                                                                                                                                                                                                          
          "readying" : { },                                                                                                                                                                                                                   
          "assuring" : { },                                                                                                                                                                                                                   
          "signing" : { },                                                                                                                                                                                                                    
          "encrypting" : { },                                                                                                                                                                                                                 
          "sending" : { },                                                                                                                                                                                                                    
          "receiving" : { },                                                                                                                                                                                                                  
          "decrypting" : { },                                                                                                                                                                                                                 
          "verifying" : { },                                                                                                                                                                                                                  
          "dropping" : { },                                                                                                                                                                                                                   
          "restoring" : { },                                                                                                                                                                                                                  
          "inserting" : { }                                                                                                                                                                                                                   
        },                                                                                                                                                                                                                                    
        "transforming" : {                                                                                                                                                                                                                    
          "selecting" : { },                                                                                                                                                                                                                  
          "filtering" : { },                                                                                                                                                                                                                  
          "supplementing" : { },                                                                                                                                                                                                              
          "recontextualising" : { },                                                                                                                                                                                                          
          "readying" : { },                                                                                                                                                                                                                   
          "assuring" : { },                                                                                                                                                                                                                   
          "signing" : { },                                                                                                                                                                                                                    
          "encrypting" : { },                                                                                                                                                                                                                 
          "sending" : { },                                                                                                                                                                                                                    
          "receiving" : { },                                                                                                                                                                                                                  
          "decrypting" : { },                                                                                                                                                                                                                 
          "verifying" : { },                                                                                                                                                                                                                  
          "dropping" : { },                                                                                                                                                                                                                   
          "restoring" : { },                                                                                                                                                                                                                  
          "inserting" : { }                                                                                                                                                                                                                   
        },                                                                                                                                                                                                                                    
        "loading" : {                                                                                                                                                                                                                         
          "selecting" : { },                                                                                                                                                                                                                  
          "filtering" : { },                                                                                                                                                                                                                  
          "supplementing" : { },                                                                                                                                                                                                              
          "recontextualising" : { },                                                                                                                                                                                                          
          "readying" : { },                                                                                                                                                                                                                   
          "assuring" : { },                                                                                                                                                                                                                   
          "signing" : { },                                                                                                                                                                                                                    
          "encrypting" : { },                                                                                                                                                                                                                 
          "sending" : { },                                                                                                                                                                                                                    
          "receiving" : { },                                                                                                                                                                                                                  
          "decrypting" : { },                                                                                                                                                                                                                 
          "verifying" : { },                                                                                                                                                                                                                  
          "dropping" : { },                                                                                                                                                                                                                   
          "restoring" : { },                                                                                                                                                                                                                  
          "inserting" : { }                                                                                                                                                                                                                   
        }                                                                                                                                                                                                                                     
      },                                                                                                                                                                                                                                      
      "receiving" : {                                                                                                                                                                                                                         
        "unloading" : {                                                                                                                                                                                                                       
          "selecting" : { },                                                                                                                                                                                                                  
          "filtering" : { },                                                                                                                                                                                                                  
          "supplementing" : { },                                                                                                                                                                                                              
          "recontextualising" : { },                                                                                                                                                                                                          
          "readying" : { },                                                                                                                                                                                                                   
          "assuring" : { },                                                                                                                                                                                                                   
          "signing" : { },                                                                                                                                                                                                                    
          "encrypting" : { },                                                                                                                                                                                                                 
          "sending" : { },                                                                                                                                                                                                                    
          "receiving" : { },                                                                                                                                                                                                                  
          "decrypting" : { },                                                                                                                                                                                                                 
          "verifying" : { },                                                                                                                                                                                                                  
          "dropping" : { },                                                                                                                                                                                                                   
          "restoring" : { },                                                                                                                                                                                                                  
          "inserting" : { }                                                                                                                                                                                                                   
        },                                                                                                                                                                                                                                    
        "transforming" : {                                                                                                                                                                                                                    
          "selecting" : { },                                                                                                                                                                                                                  
          "filtering" : { },                                                                                                                                                                                                                  
          "supplementing" : { },                                                                                                                                                                                                              
          "recontextualising" : { },                                                                                                                                                                                                          
          "readying" : { },                                                                                                                                                                                                                   
          "assuring" : { },                                                                                                                                                                                                                   
          "signing" : { },                                                                                                                                                                                                                    
          "encrypting" : { },                                                                                                                                                                                                                 
          "sending" : { },                                                                                                                                                                                                                    
          "receiving" : { },                                                                                                                                                                                                                  
          "decrypting" : { },                                                                                                                                                                                                                 
          "verifying" : { },                                                                                                                                                                                                                  
          "dropping" : { },                                                                                                                                                                                                                   
          "restoring" : { },                                                                                                                                                                                                                  
          "inserting" : { }                                                                                                                                                                                                                   
        },                                                                                                                                                                                                                                    
        "storing" : {                                                                                                                                                                                                                         
          "selecting" : { },                                                                                                                                                                                                                  
          "filtering" : { },                                                                                                                                                                                                                  
          "supplementing" : { },                                                                                                                                                                                                              
          "recontextualising" : { },                                                                                                                                                                                                          
          "readying" : { },                                                                                                                                                                                                                   
          "assuring" : { },                                                                                                                                                                                                                   
          "signing" : { },                                                                                                                                                                                                                    
          "encrypting" : { },                                                                                                                                                                                                                 
          "sending" : { },                                                                                                                                                                                                                    
          "receiving" : { },                                                                                                                                                                                                                  
          "decrypting" : { },                                                                                                                                                                                                                 
          "verifying" : { },                                                                                                                                                                                                                  
          "dropping" : { },                                                                                                                                                                                                                   
          "restoring" : { },                                                                                                                                                                                                                  
          "inserting" : { }                                                                                                                                                                                                                   
        }                                                                                                                                                                                                                                     
      }                                                                                                                                                                                                                                       
    },                                                                                                                                                                                                                                        
    "compartments" : { },                                                                                                                                                                                                                     
    "items" : [ {                                                                                                                                                                                                                             
      "transportation" : {                                                                                                                                                                                                                    
        "path" : "/job/compartments/properties/@id=13/data/assessments/@id=13"                                                                                                                                                                
      },                                                                                                                                                                                                                                      
      "persistence" : {                                                                                                                                                                                                                       
        "place" : "LTX-DOM-AST",                                                                                                                                                                                                              
        "identifier" : 13                                                                                                                                                                                                                     
      }                                                                                                                                                                                                                                       
    }, {                                                                                                                                                                                                                                      
      "transportation" : {                                                                                                                                                                                                                    
        "path" : "/job/compartments/persons/@id=16/items/@id=13"                                                                                                                                                                              
      },                                                                                                                                                                                                                                      
      "persistence" : {                                                                                                                                                                                                                       
        "place" : "LTX-DOM-PSA",                                                                                                                                                                                                              
        "identifier" : 13                                                                                                                                                                                                                     
      }                                                                                                                                                                                                                                       
    } ]                                                                                                                                                                                                                                       
  } ]                                                                                                                                                                                                                                         
}
      """.stripMargin)

    WsClient.post(
      uri = baseUri,
      headers = headers,
      json = json
    )
  }
}
